sudo: required

language: ruby

services:
  - docker

before_install:
- rake docker_pull
- rake docker_run
- docker ps -a

script:
- bundle exec rake test

after_script:
- rake docker_show_logs

rvm:
- 2.0.0
- 2.1.10
- 2.2.5
- 2.3.1

deploy:
  provider: rubygems
  api_key:
    secure: EKpsyP07VCbhH4Y/kF00ylB14R1iRekrmqcsC6No1Cf2dELwqeypQfwo3lLTZXhB0DjjgZSuXcnzw+QRTx+xZ6U7gsLrGDoKMd/irr+TBb2qyQhSBmjYuxHAWnRBtFdxWztsh77qi2SVDG7VIaJ94HnTTEjvaRhabsrOUI80MD8=
